sprawdzanie neta

diff --git a/NeteXt73 b/NeteXt73
--- a/NeteXt73
+++ b/NeteXt73
@@ -58,9 +58,13 @@ fi
 }
 
 sumy(){
-#pobranie sum kontrolnych
+#pobranie sum kontrolnych i sprawdzanie połączenia z netem
 	cd /tmp
 	wget $adres_sum_kontrolnych 2>&1 | pobieranie && mv sumy.txt $sumy_kontrolne
+	if [ "$(cat $sumy_kontrolne)" = "" ]; then
+		yad-netext --center --info --title="$nazwa_skryptu   " --text="<span color=\"$kolor_textu\"><b>$BRAKNETA</b></span>" --window-icon="/opt/NeteXt73/ikony/error.png" --image="/opt/NeteXt73/ikony/error.png" --button="gtk-ok:0" --on-top
+		exit 1
+	fi
 }
 
 #ostrzeżenie o konfliktach
