dodanie yad_wget

diff --git a/procedury b/procedury
--- a/procedury
+++ b/procedury
@@ -166,11 +166,6 @@ fi
 #########################################################################################################################################################################
 #procedury
 
-#pasek postępu pobierania dla dużych plików
-pobieranie(){
-sed -u "$TEXT_POB1" | yad-netext --center --width=610 --progress --title="$TEXT_POB2 $a $MB" --auto-close --auto-kill --window-icon="/opt/NeteXt73/ikony/download.png" --button="$TEXT_POWROT:1"
-}
-
 #pasek postępu pobierania pulsujący gdy coś długo trwa
 pobieranie2(){
 yad-netext --center --width=560 --title="$nazwa_skryptu" --text="$TEXT_POBIERANIE" --progress --pulsate --auto-close --auto-kill --window-icon="/opt/NeteXt73/ikony/download.png" --button="$TEXT_POWROT:1"
@@ -191,33 +186,15 @@ done
 #pobieranie plików do instalacji kerneli
 pobieranie_kerneli(){
 if [ "$kern" = "ppa mainline" ];then
-	wget $strona/$a 2>&1    | pobieranie 
-	zamknij_program
-	dziala=0; MB1=$(echo "scale=2;$(wget --server-response --spider $strona/$a/$(grep "href=" ./$a | cut -d '"' -f 8 | grep "all" | grep "linux-headers") 2>&1 | grep "ontent.*ength" | awk '{print $2}')/1024/1024"|bc); MB="- $MB1 MB"
-	wget $strona/$a/$(grep "href=" ./$a | cut -d '"' -f 8 | grep "all" | grep "linux-headers")      2>&1 | pobieranie 
-	zamknij_program
-	dziala=0; MB1=$(echo "scale=2;$(wget --server-response --spider $strona/$a/$(grep "href=" ./$a | cut -d '"' -f 8 | grep $bit2 | grep "linux-headers") 2>&1 | grep ength | awk '{print $2}')/1024/1024"|bc); MB="- $MB1 MB"
-	wget $strona/$a/$(grep "href=" ./$a | cut -d '"' -f 8 | grep $bit2 | grep "linux-headers")      2>&1 | pobieranie 
-	zamknij_program
-	dziala=0; MB1=$(echo "scale=2;$(wget --server-response --spider $strona/$a/$(grep "href=" ./$a | cut -d '"' -f 8 | grep $bit2 | grep "linux-image") 2>&1   | grep ength | awk '{print $2}')/1024/1024"|bc); MB="- $MB1 MB"
-	wget $strona/$a/$(grep "href=" ./$a | cut -d '"' -f 8 | grep $bit2 | grep "linux-image")        2>&1 | pobieranie 
-	zamknij_program
-	if [ "$WERSJA_DISTRO" != "saucy" ]; then
-		dziala=0; MB1=$(echo "scale=2;$(wget --server-response --spider $strona/$a/$(grep "href=" ./$a | cut -d '"' -f 8 | grep $bit2 | grep "linux-image-extra") 2>&1 | grep ength | awk '{print $2}')/1024/1024"|bc); MB="- $MB1 MB"
-		wget $strona/$a/$(grep "href=" ./$a | cut -d '"' -f 8 | grep $bit2 | grep "linux-image-extra")  2>&1 | pobieranie  
-		zamknij_program
+	wget $strona/$a 2>&1  | pobieranie2 
+	if [ "$(grep extra inxex.html)" != "" ]; then
+	    yad_wget $strona/$a/$(grep "href=" ./$a | cut -d '"' -f 8 | grep "all" | grep "linux-headers" | grep -v -E "latency") $strona/$a/$(grep "href=" ./$a | cut -d '"' -f 8 | grep $bit2 | grep "linux-headers"| grep -v -E "latency") $strona/$a/$(grep "href=" ./$a | cut -d '"' -f 8 | grep $bit2 | grep "linux-image"| grep -v -E "latency")  $strona/$a/$(grep "href=" ./$a | cut -d '"' -f 8 | grep $bit2 | grep "linux-image-extra" | grep "linux-image"| grep -v -E "latency")
+	else
+	    yad_wget $strona/$a/$(grep "href=" ./$a | cut -d '"' -f 8 | grep "all" | grep "linux-headers" | grep -v -E "latency") $strona/$a/$(grep "href=" ./$a | cut -d '"' -f 8 | grep $bit2 | grep "linux-headers"| grep -v -E "latency") $strona/$a/$(grep "href=" ./$a | cut -d '"' -f 8 | grep $bit2 | grep "linux-image"| grep -v -E "latency")
 	fi
 else
-
 #pobieranie kerneli e X t 7 3
-	wget $strona/$a/1.txt 2>&1 | pobieranie 
-	zamknij_program
-	dziala=0; MB1=$(echo "scale=2;$(wget --server-response --spider $strona/$a/$(grep "href=" ./index.html   | cut -d '"' -f 2 | grep  $rodzaj | grep $bit2 | grep "linux-headers") 2>&1 | grep "ontent.*ength" | awk '{print $2}')/1024/1024"|bc); MB="- $MB1 MB"
-	wget $strona/$a/$(grep "href=" ./index.html   | cut -d '"' -f 2 | grep  $rodzaj | grep $bit2 | grep "linux-headers") 2>&1 | pobieranie 
-	zamknij_program
-	dziala=0; MB1=$(echo "scale=2;$(wget --server-response --spider $strona/$a/$(grep "href=" ./index.html   | cut -d '"' -f 2 | grep  $rodzaj | grep $bit2 | grep "linux-image") 2>&1 | grep "ontent.*ength" | awk '{print $2}')/1024/1024"|bc); MB="- $MB1 MB"
-	wget $strona/$a/$(grep "href=" ./index.html   | cut -d '"' -f 2 | grep  $rodzaj | grep $bit2 | grep "linux-image")   2>&1 | pobieranie  
-	zamknij_program
+	yad_wget $strona/$a/1.txt $strona/$a/$(grep "href=" ./index.html   | cut -d '"' -f 2 | grep  $rodzaj | grep $bit2 | grep "linux-headers" ) $strona/$a/$(grep "href=" ./index.html   | cut -d '"' -f 2 | grep  $rodzaj | grep $bit2 | grep "linux-image")
 fi
 rm ./index.html -f
 }
@@ -666,13 +643,6 @@ echo "sudo rm -f /usr/share/applications/nvidia-settings.desktop"
 }
 
 
-zamknij_program(){
-if [ "$dziala" = "1" ]; then
-      yad-netext --center --error --title="$nazwa_skryptu"  --window-icon="/opt/NeteXt73/ikony/error.png" --image="/opt/NeteXt73/ikony/error.png" --button="gtk-ok:0"  --timeout=25 --title="$TEXT_UWAGA" --text="$TEXT_ZAMNIJ_PROGRAM"
-      exit 1
-fi
-}
-
 RAMIK_USUN(){
 echo "sudo sed /var/spool/cron/crontabs/root -i -e '/then sync && echo 3/ d'"
 echo "sudo sed /var/spool/cron/crontabs/root -i -e '/freemem.sh/ d'"
@@ -844,5 +814,113 @@ done
 x-terminal-emulator -e bash -c "htop"
 }
 
+yad_wget(){
+
+# NAME:         yad_wget
+# VERSION:      0.2
+# AUTHOR:       (c) 2014 Glutanimate
+# DESCRIPTION:  graphical frontend to wget in form of a yad script
+# FEATURES:     - display progress of multiple simultaneous downloads
+#               - set maximum number of simultaneous downloads
+# DEPENDENCIES: yad
+#
+#               Install yad on Ubuntu with:
+#
+#                   sudo add-apt-repository ppa:webupd8team/y-ppa-manager
+#                   sudo apt-get update
+#                   sudo apt-get install yad
+#
+# LICENSE:      GNU GPLv3 (http://www.gnu.de/documents/gpl-3.0.en.html)
+#
+# NOTICE:       THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY APPLICABLE LAW. 
+#               EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR OTHER PARTIES 
+#               PROVIDE THE PROGRAM “AS IS” WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR 
+#               IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY 
+#               AND FITNESS FOR A PARTICULAR PURPOSE. THE ENTIRE RISK AS TO THE QUALITY AND 
+#               PERFORMANCE OF THE PROGRAM IS WITH YOU. SHOULD THE PROGRAM PROVE DEFECTIVE,
+#               YOU ASSUME THE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.
+#
+#               IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING WILL ANY 
+#               COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MODIFIES AND/OR CONVEYS THE PROGRAM AS 
+#               PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES, INCLUDING ANY GENERAL, SPECIAL, 
+#               INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE 
+#               THE PROGRAM (INCLUDING BUT NOT LIMITED TO LOSS OF DATA OR DATA BEING RENDERED 
+#               INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD PARTIES OR A FAILURE OF THE 
+#               PROGRAM TO OPERATE WITH ANY OTHER PROGRAMS), EVEN IF SUCH HOLDER OR OTHER 
+#               PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
+#
+# USAGE:        yad_wget <space-delimited URLs>
+#               Closing the yad dialog will terminate all downloads in progress
+
+# Variables and settings
+
+MAXDLS="5" # set maximum number of simultaneous downloads
+
+URILIST="$@" # gets list of URIs from stdin
+USAGE="$0 <space-delimited URLs>"
+
+# Set GUI variables up
+TITLE="$nazwa_skryptu -YAD_wget"                 # dialog title
+TEXT="<b>$TEXT_POB2</b>"        # dialog text
+ICON="emblem-downloads"                     # window icon (appears in launcher)
+IMAGE="browser-download"                    # window image (appears in dialog)
+
+#URILIST="http://proof.ovh.net/files/100Mb.dat http://speedtest.wdc01.softlayer.com/downloads/test10.zip http://cachefly.cachefly.net/100mb.test"
+
+# Usage checks
+
+if [[ -z "$URILIST" ]]
+  then
+      echo "Error: No arguments provided"
+      echo "Usage: $USAGE"
+      exit 1
+fi
 
 
+# download file and extract progress, speed and ETA from wget
+# we use sed regex for this
+# source: http://ubuntuforums.org/showthread.php?t=306515&page=2&p=7455412#post7455412
+# modified to work with different locales and decimal point conventions
+download(){
+    wget  "$1" 2>&1 | sed -u \
+    "s/.* \([0-9]\+%\)\ \+\([0-9,.]\+.\) \(.*\)/$2:\1\n$2:#  \2\/s,  \3/"
+    RET_WGET="${PIPESTATUS[0]}"             # get return code of wget
+    if [[ "$RET_WGET" = 0 ]]                # check return code for errors
+      then
+          echo "$2:100%"
+          echo "$2:#$TEXT_POBIERANIE_GOTOWE"
+      else
+          echo "$2:#$TEXT_BLAD_POBIERANIA"
+    fi
+}
+
+
+# compose list of bars for yad
+for URI in $URILIST; do                     # iterate through all URIs
+    FILENAME="${URI##*/}"                   # extract last field of URI as filename
+    YADBARS="$YADBARS --bar=$(echo $FILENAME | sed "s/1.txt/$TEXT_SUMY_KONTROLNE/"):NORM" # add filename to the list of URIs
+done
+
+IFS=" "
+COUNTER="1"
+DYNAMIC_COUNTER="1"
+
+# main
+# iterate through all URIs, download them in the background and 
+# pipe all output simultaneously to yad
+# source: http://pastebin.com/yBL2wjaY
+
+for URI in $URILIST; do
+    if [[ "$DYNAMIC_COUNTER" = "$MAXDLS" ]] # only download n files at a time
+      then
+          download "$URI" "$COUNTER"        # if limit reached wait until wget complete
+          DYNAMIC_COUNTER="1"               # before proceeding (by not sending download() to bg)
+      else
+          download "$URI" "$COUNTER" &      # pass URI and URI number to download()
+          DYNAMIC_COUNTER="$[$DYNAMIC_COUNTER+1]"
+    fi
+    COUNTER="$[$COUNTER+1]"                 # increment counter
+done | yad-netext --center --multi-progress --auto-kill --auto-close $YADBARS --title "$TITLE" \
+--text "$TEXT" --window-icon "$ICON" --image "$IMAGE" --button="$TEXT_ZAMKNIJ:1"
+# ↑ launch yad multi progress-bar window 
+}
